/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Sources.Classes.Juices.AvocdoJuice;
import Sources.Classes.Juices.OrangeJuice;
import Sources.Classes.Juices.PomegranateJuice;
import Sources.Classes.Juices.StrawberryJuice;
import Sources.Classes.Toppings.CashewNuts;
import Sources.Classes.Toppings.VanillaIceCream;
import Sources.Classes.Toppings.WhippingCream;
import Sources.Interfaces.FreashFruiti_Juice;
import com.sun.prism.j2d.J2DPipeline;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author grays
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    FreashFruiti_Juice juice;
    static double tot;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        juiceGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totPrice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        orangeJuice = new javax.swing.JRadioButton();
        strawberryJuice = new javax.swing.JRadioButton();
        pomegranateJuice = new javax.swing.JRadioButton();
        avocadoJuice = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Treset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        iceCream = new javax.swing.JCheckBox();
        cNuts = new javax.swing.JCheckBox();
        wCream = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/29854 (Custom) (1).jpg"))); // NOI18N
        jLabel1.setText("Fresh Fruiti");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(0);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Price");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totPrice.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        totPrice.setForeground(new java.awt.Color(0, 0, 204));
        totPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totPrice.setText("00.00");
        totPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_paper_money_35px.png"))); // NOI18N
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        juiceGroup.add(orangeJuice);
        orangeJuice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        orangeJuice.setText("Orange");
        orangeJuice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        orangeJuice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        orangeJuice.setIconTextGap(0);
        orangeJuice.setOpaque(false);
        orangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeJuiceActionPerformed(evt);
            }
        });

        juiceGroup.add(strawberryJuice);
        strawberryJuice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        strawberryJuice.setText("Strawberry");
        strawberryJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryJuiceActionPerformed(evt);
            }
        });

        juiceGroup.add(pomegranateJuice);
        pomegranateJuice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pomegranateJuice.setText("Pomegranate");
        pomegranateJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomegranateJuiceActionPerformed(evt);
            }
        });

        juiceGroup.add(avocadoJuice);
        avocadoJuice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avocadoJuice.setText("Avocado");
        avocadoJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avocadoJuiceActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_strawberry_35px.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_half_orange_35px_2.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_pomegranate_35px.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_avocado_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(orangeJuice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(strawberryJuice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pomegranateJuice)
                    .addComponent(avocadoJuice))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(avocadoJuice)
                        .addComponent(orangeJuice))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pomegranateJuice)
                        .addComponent(strawberryJuice))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Treset.setBackground(new java.awt.Color(255, 255, 255));
        Treset.setForeground(new java.awt.Color(0, 0, 0));
        Treset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_reset_35px.png"))); // NOI18N
        Treset.setBorder(null);
        Treset.setBorderPainted(false);
        Treset.setContentAreaFilled(false);
        Treset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresetActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        iceCream.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        iceCream.setText("Vanila Ice Cream");
        iceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iceCreamActionPerformed(evt);
            }
        });
        jPanel1.add(iceCream, java.awt.BorderLayout.CENTER);

        cNuts.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cNuts.setText("Cashew Nuts");
        cNuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNutsActionPerformed(evt);
            }
        });
        jPanel1.add(cNuts, java.awt.BorderLayout.PAGE_START);

        wCream.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        wCream.setText("Whipping Cream");
        wCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wCreamActionPerformed(evt);
            }
        });
        jPanel1.add(wCream, java.awt.BorderLayout.PAGE_END);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_cashew_35px.png"))); // NOI18N
        jLabel7.setToolTipText("");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_kawaii_ice_cream_35px_1.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_confectionery_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Treset)
                        .addGap(19, 19, 19))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Treset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(totPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void avocadoJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avocadoJuiceActionPerformed
        juice = new AvocdoJuice();
        avocadoJuice.setMnemonic(0);
        tot = juice.getPrice();
        totPrice.setText("Rs: " + String.valueOf(tot));
    }//GEN-LAST:event_avocadoJuiceActionPerformed

    private void orangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeJuiceActionPerformed
        juice = new OrangeJuice();
        orangeJuice.setMnemonic(1);
        tot = juice.getPrice();
        totPrice.setText("Rs: " + String.valueOf(tot));
    }//GEN-LAST:event_orangeJuiceActionPerformed

    private void strawberryJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryJuiceActionPerformed
        juice = new StrawberryJuice();
        strawberryJuice.setMnemonic(2);
        tot = juice.getPrice();
        totPrice.setText("Rs: " + String.valueOf(tot));
    }//GEN-LAST:event_strawberryJuiceActionPerformed

    private void pomegranateJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomegranateJuiceActionPerformed
        juice = new PomegranateJuice();
        tot = juice.getPrice();
        pomegranateJuice.setMnemonic(3);
        totPrice.setText("Rs: " + String.valueOf(tot));
    }//GEN-LAST:event_pomegranateJuiceActionPerformed

    private void iceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iceCreamActionPerformed
        if (iceCream.isSelected()) {
            if (juice != null) {
                juice = new VanillaIceCream(juice);
                tot = juice.getPrice();
                totPrice.setText("Rs: " + String.valueOf(tot));
            } else {
                JOptionPane.showMessageDialog(this, "Select Juice To Add Toppings", "Error", JOptionPane.ERROR_MESSAGE);
                iceCream.setSelected(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Reset Toppings by Reset Button", "Error", JOptionPane.ERROR_MESSAGE);
            iceCream.setSelected(true);
        }

    }//GEN-LAST:event_iceCreamActionPerformed

    private void wCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wCreamActionPerformed

        if (wCream.isSelected()) {
            if (juice != null) {
                juice = new WhippingCream(juice);
                tot = juice.getPrice();
                totPrice.setText("Rs: " + String.valueOf(tot));
            } else {
                JOptionPane.showMessageDialog(this, "Select Juice To Add Toppings", "Error", JOptionPane.ERROR_MESSAGE);
                wCream.setSelected(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Reset Toppings by Reset Button", "Error", JOptionPane.ERROR_MESSAGE);
            wCream.setSelected(true);
        }

    }//GEN-LAST:event_wCreamActionPerformed

    private void cNutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNutsActionPerformed

        if (cNuts.isSelected()) {
            if (juice != null) {

                juice = new CashewNuts(juice);
                tot = juice.getPrice();
                totPrice.setText("Rs: " + String.valueOf(tot));

            } else {
                JOptionPane.showMessageDialog(this, "Select Juice To Add Toppings", "Error", JOptionPane.ERROR_MESSAGE);
                cNuts.setSelected(false);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Reset Toppings by Reset Button", "Error", JOptionPane.ERROR_MESSAGE);
            cNuts.setSelected(true);
        }

    }//GEN-LAST:event_cNutsActionPerformed

    void Reset() {
        juice = null;
        tot = 0.0;
//        orangeJuice.setSelected(false);
//        avocadoJuice.setSelected(false);
//        strawberryJuice.setSelected(false);
//        pomegranateJuice.setSelected(false);

        juiceGroup.clearSelection();
        totPrice.setText(String.valueOf(tot));
        cNuts.setSelected(false);
        wCream.setSelected(false);
        iceCream.setSelected(false);

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (juice != null) {
            JOptionPane.showMessageDialog(this, juice.getDescription() + "\n Price = Rs: " + juice.getPrice(), "Payment Success", JOptionPane.INFORMATION_MESSAGE);
            Reset();

        } else {
            JOptionPane.showMessageDialog(this, "Select your Favourations ", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresetActionPerformed
        if (juice != null) {
            wCream.setSelected(false);
            cNuts.setSelected(false);
            iceCream.setSelected(false);
            if (juiceGroup.getSelection().getMnemonic() == 0) {
                avocadoJuiceActionPerformed(evt);
            } else if (juiceGroup.getSelection().getMnemonic() == 1) {
                orangeJuiceActionPerformed(evt);
            } else if (juiceGroup.getSelection().getMnemonic() == 2) {
                strawberryJuiceActionPerformed(evt);
            } else if (juiceGroup.getSelection().getMnemonic() == 3) {
                pomegranateJuiceActionPerformed(evt);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select Juice First", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home h = new Home();
                h.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Resources/ico.png")));
                h.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Treset;
    private javax.swing.JRadioButton avocadoJuice;
    private javax.swing.JCheckBox cNuts;
    private javax.swing.JCheckBox iceCream;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.ButtonGroup juiceGroup;
    private javax.swing.JRadioButton orangeJuice;
    private javax.swing.JRadioButton pomegranateJuice;
    private javax.swing.JRadioButton strawberryJuice;
    private javax.swing.JLabel totPrice;
    private javax.swing.JCheckBox wCream;
    // End of variables declaration//GEN-END:variables
}
