/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Sources.ArithmaticValue;
import Sources.AstrixOperator;
import Sources.BackSlashOperator;
import Sources.MinusOperator;
import Sources.PlusOperator;
import Sources.Number;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author grays
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    ArrayList<String> valueList;

    public Home() {
        initComponents();
        valueList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        answerDisplay = new javax.swing.JLabel();
        activityDisplay = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        divide_btn = new javax.swing.JButton();
        seven_btn = new javax.swing.JButton();
        eight_btn = new javax.swing.JButton();
        nine_btn = new javax.swing.JButton();
        multipy_btn = new javax.swing.JButton();
        four_btn = new javax.swing.JButton();
        six_btn = new javax.swing.JButton();
        minus_btn = new javax.swing.JButton();
        five_btn = new javax.swing.JButton();
        three_btn = new javax.swing.JButton();
        one_btn = new javax.swing.JButton();
        two_btn = new javax.swing.JButton();
        plus_btn = new javax.swing.JButton();
        zero_btn = new javax.swing.JButton();
        equal_btn = new javax.swing.JButton();
        dot_btn = new javax.swing.JButton();
        seven_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        answerDisplay.setBackground(new java.awt.Color(0, 0, 255));
        answerDisplay.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        answerDisplay.setForeground(new java.awt.Color(0, 0, 0));
        answerDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerDisplay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        answerDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        activityDisplay.setBackground(new java.awt.Color(0, 0, 255));
        activityDisplay.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        activityDisplay.setForeground(new java.awt.Color(0, 0, 0));
        activityDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activityDisplay.setText("0.0");
        activityDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        divide_btn.setBackground(new java.awt.Color(0, 102, 102));
        divide_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        divide_btn.setForeground(new java.awt.Color(255, 255, 51));
        divide_btn.setText("/");
        divide_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        divide_btn.setBorderPainted(false);
        divide_btn.setContentAreaFilled(false);
        divide_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divide_btn.setOpaque(true);
        divide_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_btnActionPerformed(evt);
            }
        });

        seven_btn.setBackground(new java.awt.Color(0, 0, 0));
        seven_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        seven_btn.setForeground(new java.awt.Color(255, 255, 255));
        seven_btn.setText("7");
        seven_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        seven_btn.setBorderPainted(false);
        seven_btn.setContentAreaFilled(false);
        seven_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seven_btn.setFocusPainted(false);
        seven_btn.setOpaque(true);
        seven_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_btnActionPerformed(evt);
            }
        });

        eight_btn.setBackground(new java.awt.Color(0, 0, 0));
        eight_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        eight_btn.setForeground(new java.awt.Color(255, 255, 255));
        eight_btn.setText("8");
        eight_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        eight_btn.setBorderPainted(false);
        eight_btn.setContentAreaFilled(false);
        eight_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eight_btn.setOpaque(true);
        eight_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_btnActionPerformed(evt);
            }
        });

        nine_btn.setBackground(new java.awt.Color(0, 0, 0));
        nine_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        nine_btn.setForeground(new java.awt.Color(255, 255, 255));
        nine_btn.setText("9");
        nine_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        nine_btn.setBorderPainted(false);
        nine_btn.setContentAreaFilled(false);
        nine_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nine_btn.setOpaque(true);
        nine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_btnActionPerformed(evt);
            }
        });

        multipy_btn.setBackground(new java.awt.Color(0, 102, 102));
        multipy_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        multipy_btn.setForeground(new java.awt.Color(255, 255, 51));
        multipy_btn.setText("x");
        multipy_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        multipy_btn.setBorderPainted(false);
        multipy_btn.setContentAreaFilled(false);
        multipy_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multipy_btn.setOpaque(true);
        multipy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipy_btnActionPerformed(evt);
            }
        });

        four_btn.setBackground(new java.awt.Color(0, 0, 0));
        four_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        four_btn.setForeground(new java.awt.Color(255, 255, 255));
        four_btn.setText("4");
        four_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        four_btn.setBorderPainted(false);
        four_btn.setContentAreaFilled(false);
        four_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        four_btn.setOpaque(true);
        four_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_btnActionPerformed(evt);
            }
        });

        six_btn.setBackground(new java.awt.Color(0, 0, 0));
        six_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        six_btn.setForeground(new java.awt.Color(255, 255, 255));
        six_btn.setText("6");
        six_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        six_btn.setBorderPainted(false);
        six_btn.setContentAreaFilled(false);
        six_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        six_btn.setOpaque(true);
        six_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_btnActionPerformed(evt);
            }
        });

        minus_btn.setBackground(new java.awt.Color(0, 102, 102));
        minus_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        minus_btn.setForeground(new java.awt.Color(255, 255, 51));
        minus_btn.setText("-");
        minus_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        minus_btn.setBorderPainted(false);
        minus_btn.setContentAreaFilled(false);
        minus_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minus_btn.setOpaque(true);
        minus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minus_btnActionPerformed(evt);
            }
        });

        five_btn.setBackground(new java.awt.Color(0, 0, 0));
        five_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        five_btn.setForeground(new java.awt.Color(255, 255, 255));
        five_btn.setText("5");
        five_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        five_btn.setBorderPainted(false);
        five_btn.setContentAreaFilled(false);
        five_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        five_btn.setOpaque(true);
        five_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_btnActionPerformed(evt);
            }
        });

        three_btn.setBackground(new java.awt.Color(0, 0, 0));
        three_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        three_btn.setForeground(new java.awt.Color(255, 255, 255));
        three_btn.setText("3");
        three_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        three_btn.setBorderPainted(false);
        three_btn.setContentAreaFilled(false);
        three_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        three_btn.setOpaque(true);
        three_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_btnActionPerformed(evt);
            }
        });

        one_btn.setBackground(new java.awt.Color(0, 0, 0));
        one_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        one_btn.setForeground(new java.awt.Color(255, 255, 255));
        one_btn.setText("1");
        one_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        one_btn.setBorderPainted(false);
        one_btn.setContentAreaFilled(false);
        one_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        one_btn.setOpaque(true);
        one_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_btnActionPerformed(evt);
            }
        });

        two_btn.setBackground(new java.awt.Color(0, 0, 0));
        two_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        two_btn.setForeground(new java.awt.Color(255, 255, 255));
        two_btn.setText("2");
        two_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        two_btn.setBorderPainted(false);
        two_btn.setContentAreaFilled(false);
        two_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two_btn.setOpaque(true);
        two_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_btnActionPerformed(evt);
            }
        });

        plus_btn.setBackground(new java.awt.Color(0, 102, 102));
        plus_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        plus_btn.setForeground(new java.awt.Color(255, 255, 51));
        plus_btn.setText("+");
        plus_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        plus_btn.setBorderPainted(false);
        plus_btn.setContentAreaFilled(false);
        plus_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus_btn.setOpaque(true);
        plus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_btnActionPerformed(evt);
            }
        });

        zero_btn.setBackground(new java.awt.Color(0, 0, 0));
        zero_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        zero_btn.setForeground(new java.awt.Color(255, 255, 255));
        zero_btn.setText("0");
        zero_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        zero_btn.setBorderPainted(false);
        zero_btn.setContentAreaFilled(false);
        zero_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zero_btn.setOpaque(true);
        zero_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_btnActionPerformed(evt);
            }
        });

        equal_btn.setBackground(new java.awt.Color(0, 102, 102));
        equal_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        equal_btn.setForeground(new java.awt.Color(255, 255, 51));
        equal_btn.setText("=");
        equal_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        equal_btn.setBorderPainted(false);
        equal_btn.setContentAreaFilled(false);
        equal_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equal_btn.setOpaque(true);
        equal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_btnActionPerformed(evt);
            }
        });

        dot_btn.setBackground(new java.awt.Color(0, 0, 0));
        dot_btn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        dot_btn.setForeground(new java.awt.Color(255, 255, 255));
        dot_btn.setText(".");
        dot_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255), java.awt.Color.blue, java.awt.Color.blue));
        dot_btn.setBorderPainted(false);
        dot_btn.setContentAreaFilled(false);
        dot_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dot_btn.setOpaque(true);
        dot_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dot_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zero_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(equal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(one_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(two_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(three_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(four_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(five_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(six_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(seven_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eight_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eight_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(four_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(five_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(one_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zero_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(divide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multipy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        seven_btn1.setBackground(new java.awt.Color(0, 0, 0));
        seven_btn1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        seven_btn1.setForeground(new java.awt.Color(255, 255, 255));
        seven_btn1.setText("Clear All");
        seven_btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        seven_btn1.setBorderPainted(false);
        seven_btn1.setContentAreaFilled(false);
        seven_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seven_btn1.setFocusPainted(false);
        seven_btn1.setOpaque(true);
        seven_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(answerDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seven_btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activityDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(activityDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seven_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void divide_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_btnActionPerformed
        if (answerDisplay.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mathematical error", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            answerDisplay.setText(answerDisplay.getText() + "/");
        }
    }//GEN-LAST:event_divide_btnActionPerformed

    private void seven_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "7");
    }//GEN-LAST:event_seven_btnActionPerformed

    private void eight_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "8");
    }//GEN-LAST:event_eight_btnActionPerformed

    private void nine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "9");
    }//GEN-LAST:event_nine_btnActionPerformed

    private void multipy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipy_btnActionPerformed
        if (answerDisplay.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mathematical error", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            answerDisplay.setText(answerDisplay.getText() + "*");
        }
    }//GEN-LAST:event_multipy_btnActionPerformed

    private void four_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "4");
    }//GEN-LAST:event_four_btnActionPerformed

    private void six_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "6");
    }//GEN-LAST:event_six_btnActionPerformed

    private void minus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus_btnActionPerformed
        if (answerDisplay.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mathematical error", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            answerDisplay.setText(answerDisplay.getText() + "-");
        }
    }//GEN-LAST:event_minus_btnActionPerformed

    private void five_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "5");
    }//GEN-LAST:event_five_btnActionPerformed

    private void three_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "3");
    }//GEN-LAST:event_three_btnActionPerformed

    private void one_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "1");
    }//GEN-LAST:event_one_btnActionPerformed

    private void two_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "2");
    }//GEN-LAST:event_two_btnActionPerformed

    private void plus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_btnActionPerformed
        if (answerDisplay.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mathematical error", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            answerDisplay.setText(answerDisplay.getText() + "+");
        }
    }//GEN-LAST:event_plus_btnActionPerformed

    private void zero_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + "0");
    }//GEN-LAST:event_zero_btnActionPerformed

    private void dot_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dot_btnActionPerformed
        answerDisplay.setText(answerDisplay.getText() + ".");
    }//GEN-LAST:event_dot_btnActionPerformed

    private void equal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_btnActionPerformed
        try {
            if (!answerDisplay.getText().equals("")) {
                String Text = answerDisplay.getText();

                char[] toCharArray = Text.toCharArray();
                String num = "";

                for (char u : toCharArray) {
                    String value = String.valueOf(u);
                    switch (value) {
                        case "+":
                            valueList.add(num);
                            valueList.add("+");
                            num = "";
                            break;
                        case "-":
                            valueList.add(num);
                            valueList.add("-");
                            num = "";
                            break;
                        case "*":
                            valueList.add(num);
                            valueList.add("*");
                            num = "";
                            break;
                        case "/":
                            valueList.add(num);
                            valueList.add("/");
                            num = "";
                            break;
                        default:
                            num += value;
                            break;
                    }
                }
                valueList.add(num);
                double CalculateMethod = CalculateMethod();
                answerDisplay.setText(Text);
                activityDisplay.setText(String.valueOf(CalculateMethod));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Operators are Mismatched", "Mathematical error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_equal_btnActionPerformed

    private void seven_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_btn1ActionPerformed
        answerDisplay.setText("");
        activityDisplay.setText("0.0");
        valueList.clear();
    }//GEN-LAST:event_seven_btn1ActionPerformed

    public double CalculateMethod() {

        ArithmaticValue value = new Number("0");

        for (int i = 0; i < valueList.size(); i++) {
            String get = valueList.get(i);
            switch (get) {
                case "+": {
                    ArithmaticValue nextValue = new Number(valueList.get(i + 1));
                    value = new PlusOperator(value, nextValue);
                    i++;
                    break;
                }
                case "-": {
                    ArithmaticValue nextValue = new Number(valueList.get(i + 1));
                    value = new MinusOperator(value, nextValue);
                    i++;
                    break;
                }
                case "*": {
                    ArithmaticValue nextValue = new Number(valueList.get(i + 1));
                    value = new AstrixOperator(value, nextValue);
                    i++;
                    break;
                }
                case "/": {
                    ArithmaticValue nextValue = new Number(valueList.get(i + 1));
                    value = new BackSlashOperator(value, nextValue);
                    i++;
                    break;
                }
                default:
                    value = new Number(get);
                    break;
            }
        }
        return value.interpretSum();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                home.setVisible(true);
                home.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Resources/ico.png")));
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityDisplay;
    private javax.swing.JLabel answerDisplay;
    private javax.swing.JButton divide_btn;
    private javax.swing.JButton dot_btn;
    private javax.swing.JButton eight_btn;
    private javax.swing.JButton equal_btn;
    private javax.swing.JButton five_btn;
    private javax.swing.JButton four_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton minus_btn;
    private javax.swing.JButton multipy_btn;
    private javax.swing.JButton nine_btn;
    private javax.swing.JButton one_btn;
    private javax.swing.JButton plus_btn;
    private javax.swing.JButton seven_btn;
    private javax.swing.JButton seven_btn1;
    private javax.swing.JButton six_btn;
    private javax.swing.JButton three_btn;
    private javax.swing.JButton two_btn;
    private javax.swing.JButton zero_btn;
    // End of variables declaration//GEN-END:variables
}
