package jiat.dp.ii.ex.bestPractise.models;
// Generated Jan 23, 2022 9:16:32 PM by Hibernate Tools 4.3.1



/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer vehiId;
     private String vehiName;
     private String vehiBrand;
     private String vehiEngine;
     private String vehiSeats;
     private String vehiDescrip;
     private Integer vehiType;
     private String vehiImg;

    public Vehicle() {
    }

    public Vehicle(String vehiName, String vehiBrand, String vehiEngine, String vehiSeats, String vehiDescrip, Integer vehiType, String vehiImg) {
       this.vehiName = vehiName;
       this.vehiBrand = vehiBrand;
       this.vehiEngine = vehiEngine;
       this.vehiSeats = vehiSeats;
       this.vehiDescrip = vehiDescrip;
       this.vehiType = vehiType;
       this.vehiImg = vehiImg;
    }
   
    public Integer getVehiId() {
        return this.vehiId;
    }
    
    public void setVehiId(Integer vehiId) {
        this.vehiId = vehiId;
    }
    public String getVehiName() {
        return this.vehiName;
    }
    
    public void setVehiName(String vehiName) {
        this.vehiName = vehiName;
    }
    public String getVehiBrand() {
        return this.vehiBrand;
    }
    
    public void setVehiBrand(String vehiBrand) {
        this.vehiBrand = vehiBrand;
    }
    public String getVehiEngine() {
        return this.vehiEngine;
    }
    
    public void setVehiEngine(String vehiEngine) {
        this.vehiEngine = vehiEngine;
    }
    public String getVehiSeats() {
        return this.vehiSeats;
    }
    
    public void setVehiSeats(String vehiSeats) {
        this.vehiSeats = vehiSeats;
    }
    public String getVehiDescrip() {
        return this.vehiDescrip;
    }
    
    public void setVehiDescrip(String vehiDescrip) {
        this.vehiDescrip = vehiDescrip;
    }
    public Integer getVehiType() {
        return this.vehiType;
    }
    
    public void setVehiType(Integer vehiType) {
        this.vehiType = vehiType;
    }
    public String getVehiImg() {
        return this.vehiImg;
    }
    
    public void setVehiImg(String vehiImg) {
        this.vehiImg = vehiImg;
    }




}


